<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net7.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\native_definition\Sp02NativeDefinitionBuilder.csproj" />
    <PackageReference Include="Grasshopper" Version="8.32.26160.13001" />
  </ItemGroup>
</Project>
