#!/usr/bin/env python3
"""Porsche 911 Carrera 992.2 V13 — continuous primary-shell reconstruction.

V13 keeps fender crown / rear haunch / roof / terminal form as semantic Source families, but all
visible macro form is generated by ONE continuous primary body shell. No floating roof shell,
no overlapping visible fender ellipsoids, no separate fascia slab.

Candidate projection metrics are measured from final evaluated visible geometry.
"""
from __future__ import annotations
import importlib.util,json,math
from pathlib import Path
import bpy

HERE=Path(__file__).resolve().parent
CORE=HERE/'run_reference_repro_v5.py'
CONTOUR=json.loads((HERE/'REFERENCE_CONTOUR_TARGETS_992_2.json').read_text())
PROJ=json.loads((HERE/'REFERENCE_PROJECTION_TARGETS_992_2.json').read_text())
SIDE_TOP=[tuple(map(float,p)) for p in CONTOUR['side_top_silhouette_m']]
SIDE_LOW=[tuple(map(float,p)) for p in PROJ['side']['lower_body_silhouette_m']]
spec=importlib.util.spec_from_file_location('v5core',CORE);v=importlib.util.module_from_spec(spec);spec.loader.exec_module(v)

v.REF='2025_992.2_CARRERA_CONTINUOUS_PRIMARY_SHELL_V13'
v.WIDTH_PTS=[(-2.271,.845),(-2.10,.895),(-1.85,.918),(-1.55,.926),(-1.195,.926),(-.80,.920),(-.40,.905),(0,.895),(.40,.897),(.80,.905),(1.255,.914),(1.60,.910),(1.85,.895),(2.10,.860),(2.271,.790)]
v.SPINE_PTS=[(-2.271,.590),(-2.10,.675),(-1.85,.730),(-1.55,.785),(-1.195,.820),(-.80,.825),(-.40,.820),(0,.800),(.40,.790),(.80,.790),(1.00,.790),(1.255,.775),(1.45,.750),(1.65,.690),(1.85,.600),(2.05,.555),(2.271,.460)]
v.LOWER_PTS=[(-2.271,.205),(-2.05,.195),(-1.85,.170),(-1.72,.150),(-.75,.145),(0,.145),(.90,.145),(1.72,.155),(1.86,.170),(2.05,.195),(2.271,.205)]
v.ROOF_TOP_PTS=SIDE_TOP
v.CABIN_W_PTS=[(-1.55,.505),(-1.30,.550),(-1.15,.575),(-.90,.580),(-.65,.565),(-.40,.548),(-.15,.538),(.05,.538),(.25,.545),(.45,.560),(.65,.595)]
v.BELT_PTS=[(-1.70,.775),(-1.50,.800),(-1.20,.825),(-.90,.838),(-.50,.842),(0,.840),(.40,.836),(.65,.822)]
# These are semantic section conditions, NOT separate visible meshes.
FENDER_CROWN={'front_peak_fraction':.82,'rear_peak_fraction':.88,'front_center_drop_m':.085,'rear_center_drop_m':.060,'outer_drop_m':.035}
TERMINAL_PLAN={'front_outer_setback_m':.080,'rear_outer_setback_m':.070}
v.FAMILY_CONTROLS={
 'BODY_PLAN':v.WIDTH_PTS,'HOOD_DECK_SPINE':v.SPINE_PTS,'LOWER_BODY':v.LOWER_PTS,
 'CALIBRATED_SIDE_TOP':SIDE_TOP,'ROOF_WIDTH':v.CABIN_W_PTS,'BELT':v.BELT_PTS,
 'FRONT_FENDER_CROWN':FENDER_CROWN,'REAR_HAUNCH':FENDER_CROWN,
 'ROOF_FASTBACK_CONTINUITY':{'rear_blend_x':[-1.72,-1.45],'front_blend_x':[.48,.72]},
 'TERMINAL_PLAN_CURVATURE':TERMINAL_PLAN,'GLASS_APERTURE':{'a_pillar_x':.650,'c_pillar_x':-1.150},
 'WHEEL_APERTURE':{'front_gap':.043,'rear_gap':.044}}
v.REFERENCE_CONTRACT['schema']='oleander.3d.reference-reproduction.porsche-911-992-2.v13'
v.REFERENCE_CONTRACT['reference_revision']=v.REF
v.REFERENCE_CONTRACT['source_families']=list(v.FAMILY_CONTROLS.keys())
v.REFERENCE_CONTRACT['visible_primary_shell_count']=1
v.REFERENCE_CONTRACT['visual_references']=['REFERENCE_CONTOUR_TARGETS_992_2.json','REFERENCE_PROJECTION_TARGETS_992_2.json']

# Helpers
def h(pts,x):return v.hermite(pts,x)
def s01(t):t=max(0.0,min(1.0,t));return t*t*(3-2*t)
def roof_w(x):
 if x<=-1.72 or x>=.72:return 0.0
 if x<-1.45:return s01((x+1.72)/.27)
 if x<=.48:return 1.0
 return 1.0-s01((x-.48)/.24)
def front_inf(x):return math.exp(-((x-v.FRONT_AXLE)/.62)**4)
def rear_inf(x):return math.exp(-((x-v.REAR_AXLE)/.70)**4)

def fields(x):return h(v.WIDTH_PTS,x),h(v.SPINE_PTS,x),h(v.LOWER_PTS,x),h(SIDE_TOP,x),h(v.BELT_PTS,x)
v.body_fields=lambda x:(fields(x)[0],fields(x)[1],fields(x)[3],fields(x)[2])

def crown_profile(f,target,x):
 fi=front_inf(x);ri=rear_inf(x);rear=ri>=fi;inf=max(fi,ri)
 peak=(FENDER_CROWN['rear_peak_fraction'] if rear else FENDER_CROWN['front_peak_fraction'])
 drop=(FENDER_CROWN['rear_center_drop_m'] if rear else FENDER_CROWN['front_center_drop_m'])
 # Away from wheel crowns, keep a subdued shoulder/deck relationship.
 drop=drop*(.35+.65*inf)+.020*(1-inf)
 center=target-drop
 if f<=peak:
  u=f/max(peak,1e-6);z=center+(target-center)*(math.sin(u*math.pi/2)**1.55)
 else:
  z=target-FENDER_CROWN['outer_drop_m']*((f-peak)/(1-peak))**1.25
 return z

def roof_profile(f,target,x,w,belt):
 rw=min(w*.73,max(.40,h(v.CABIN_W_PTS,x)));rf=rw/max(w,1e-6)
 if f<=rf:
  u=f/max(rf,1e-6);return target-(target-belt)*(u**1.75)
 # roof shoulder falls gently into the upper body, never becoming a second shell.
 u=(f-rf)/max(1-rf,1e-6);return belt+.018*(1-s01(u))-.018*s01(u)

def body_ring(x):
 w,zc,zl,target,belt=fields(x);rwgt=roof_w(x);fs=(0,.12,.25,.38,.52,.65,.76,.84,.91,.965,1.0)
 prelim=[]
 for f in fs:
  zcrown=crown_profile(f,target,x);zroof=roof_profile(f,target,x,w,belt);z=rwgt*zroof+(1-rwgt)*zcrown;prelim.append(z)
 # Keep the actual final visible section bound to the calibrated SIDE maximum.
 off=target-max(prelim);up=[(f*w,z+off) for f,z in zip(fs,prelim)]
 pos=up+[(.997*w,zl),(.965*w,.190),(.84*w,.146),(0,.140)]
 ft=s01((x-1.80)/(v.FRONT_X-1.80)) if x>1.80 else 0.0;rt=s01((-x-1.80)/(-v.REAR_X-1.80)) if x<-1.80 else 0.0
 out=[]
 for y,z in pos+[(-yy,zz) for yy,zz in reversed(pos[1:-1])]:
  q=abs(y)/max(w,1e-6);xe=x-TERMINAL_PLAN['front_outer_setback_m']*ft*(q**1.65)+TERMINAL_PLAN['rear_outer_setback_m']*rt*(q**1.65);out.append((xe,y,z))
 return out
v.body_ring=body_ring

# Source records semantic primary families while ownership remains one visible shell.
def build_source(M):
 verts=[];edges=[]
 for name,pts,kind in [('PLAN',v.WIDTH_PTS,'w'),('SPINE',v.SPINE_PTS,'z'),('LOWER',v.LOWER_PTS,'z'),('SIDE_TOP',SIDE_TOP,'z'),('ROOF_WIDTH',v.CABIN_W_PTS,'w'),('BELT',v.BELT_PTS,'z')]:
  st=len(verts)
  for x,val in pts:verts.append((x,val,h(v.SPINE_PTS,x)) if kind=='w' else (x,0,val))
  edges += [(st+i,st+i+1) for i in range(len(pts)-1)]
 for co in [(v.REAR_X,0,.14),(v.FRONT_X,0,.14),(v.REAR_AXLE,v.WIDTH/2,.70),(v.REAR_AXLE,-v.WIDTH/2,.70),(-.15,0,v.HEIGHT)]:verts.append(co)
 me=bpy.data.meshes.new('SRC_911_9922_V13_CONTINUOUS_SHELL_MESH');me.from_pydata(verts,edges,[]);me.update();o=bpy.data.objects.new('SRC_911_9922_V13_CONTINUOUS_SHELL',me);bpy.context.collection.objects.link(o);o.hide_render=True;o.hide_set(True);o['OLEANDER_AUTHORITY']='SPARSE_REFERENCE_REPRO_SOURCE';o['OLEANDER_VISIBLE_PRIMARY_SHELL_COUNT']=1;o['OLEANDER_SOURCE_FAMILIES']=json.dumps(list(v.FAMILY_CONTROLS));o['OLEANDER_CONTROL_DIGEST']=v.m.sha_json(v.FAMILY_CONTROLS);return o
v.build_source=build_source

# V5 main creates a second cabin mesh; V13 makes it a hidden backing only.
def cabin_ring(x):
 top=h(SIDE_TOP,x)-.055;w=max(.38,h(v.CABIN_W_PTS,x)-.04);belt=h(v.BELT_PTS,x)-.025;pos=[(0,top),(.35*w,top-.025),(.72*w,top-.090),(w,belt),(0,belt-.03)];return [(x,y,z) for y,z in pos+[(-yy,zz) for yy,zz in reversed(pos[1:-1])]]
v.cabin_ring=cabin_ring
orig_loft=v.build_loft
def build_loft(name,xs,ringfn,mat,authority,render=True):
 o=orig_loft(name,xs,ringfn,mat,authority,render)
 if name=='DERIVED_911_9922_CABIN':o.hide_render=True;o['OLEANDER_EXPOSURE_ROLE']='NON_RENDERED_BACKING'
 if name=='DERIVED_911_9922_BODY':o['OLEANDER_FORM_SYSTEM']='V13_ONE_CONTINUOUS_PRIMARY_SHELL';o['OLEANDER_VISIBLE_PRIMARY_SHELL']=True
 return o
v.build_loft=build_loft

# Apertures follow calibrated side/front/rear image evidence.
def build_glass(M):
 out=[]
 out.append(v.m.add_panel('REF_WINDSHIELD',[(.650,.622,.840),(.650,-.622,.840),(.235,-.515,1.215),(.235,.515,1.215)],M['glass'],.003))
 out.append(v.m.add_panel('REF_REAR_GLASS',[(-.390,.515,1.215),(-.390,-.515,1.215),(-1.150,-.590,.990),(-1.150,.590,.990)],M['glass'],.003))
 outline=[tuple(p) for p in PROJ['side']['glass_outline_m']]
 for side in (1,-1):
  vv=[(x,side*(max(.43,h(v.CABIN_W_PTS,x))+.006),z) for x,z in outline];out.append(v.m.add_panel('REF_SIDE_GLASS_'+('L' if side>0 else 'R'),vv,M['glass'],.003))
  out.append(v.m.add_curve('REF_A_PILLAR_'+('L' if side>0 else 'R'),[(.650,side*.622,.840),(.455,side*.575,1.055),(.235,side*.515,1.215)],M['body'],.008))
  out.append(v.m.add_curve('REF_ROOF_RAIL_'+('L' if side>0 else 'R'),[(.235,side*.515,1.215),(0,side*.505,1.282),(-.230,side*.515,1.235),(-.390,side*.515,1.215)],M['body'],.009))
  out.append(v.m.add_curve('REF_C_PILLAR_EDGE_'+('L' if side>0 else 'R'),[(-.390,side*.515,1.215),(-.760,side*.555,1.055),(-1.150,side*.590,.990)],M['body'],.010))
  out.append(v.m.add_cube('REF_B_PILLAR_'+('L' if side>0 else 'R'),(-.235,side*.555,1.020),(.026,.020,.300),M['body_dark'],.003));out.append(v.m.add_cube('REF_DOOR_HANDLE_'+('L' if side>0 else 'R'),(-.02,side*.896,.682),(.105,.012,.017),M['body_dark'],.003));y=side*.912;out.append(v.m.add_curve('REF_DOOR_SEAM_'+('L' if side>0 else 'R'),[(.595,y,.770),(.545,y,.500),(-.635,y,.500),(-.800,y,.665),(-.785,y,.825)],M['seam'],.0017))
 return out
v.build_glass=build_glass

# Thin identity features only; macro volume remains the one body shell.
def cut_sphere(host,name,loc,scale):
 bpy.ops.mesh.primitive_uv_sphere_add(segments=64,ring_count=32,location=loc);c=bpy.context.object;c.name=name;c.scale=scale;bpy.ops.object.transform_apply(location=False,rotation=False,scale=True);bo=host.modifiers.new('CUT_'+name,'BOOLEAN');bo.operation='DIFFERENCE';bo.solver='EXACT';bo.object=c;bpy.context.view_layer.objects.active=host;host.select_set(True);bpy.ops.object.modifier_apply(modifier=bo.name);bpy.data.objects.remove(c,do_unlink=True)
def build_identity(M):
 out=[];body=bpy.data.objects.get('DERIVED_911_9922_BODY')
 if body:
  for side in (1,-1):cut_sphere(body,'HEADLAMP_RECESS_'+str(side),(1.745,side*.655,.758),(.052,.138,.134))
 for side in (1,-1):
  out.append(v.m.add_uv_sphere('REF_HEADLAMP_HOUSING_'+str(side),(1.727,side*.655,.758),(.026,.126,.122),M['body_dark']));out.append(v.m.add_uv_sphere('REF_HEADLAMP_LENS_'+str(side),(1.749,side*.655,.758),(.010,.114,.110),M['glass']))
  for iy,dy in enumerate((-.034,.034)):
   for iz,dz in enumerate((-.034,.034)):out.append(v.m.add_cube(f'REF_HEADLAMP_LED_{side}_{iy}_{iz}',(1.760,side*.655+dy,.758+dz),(.006,.019,.019),M['headlamp'],.003))
  out.append(v.m.add_uv_sphere('REF_MIRROR_'+str(side),(.500,side*.940,.875),(.088,.060,.040),M['body_dark']));y=side*.525;out.append(v.m.add_curve('REF_HOOD_SEAM_'+str(side),[(.645,y,.805),(1.04,y,.790),(1.43,y,.750),(1.82,side*.455,.665)],M['seam'],.0015))
 # front lower band, visually thin and subordinate to body form
 out.append(v.m.add_cube('REF_FRONT_CENTER_INTAKE',(2.205,0,.285),(.014,.460,.072),M['body_dark'],.006))
 for side in (1,-1):
  out.append(v.m.add_cube('REF_FRONT_SIDE_INTAKE_'+str(side),(2.198,side*.520,.300),(.014,.255,.092),M['body_dark'],.008))
  for k in (-.026,0,.026):out.append(v.m.add_cube(f'REF_FRONT_SIDE_VANE_{side}_{k}',(2.190,side*.520,.300+k),(.007,.240,.005),M['rim'],.0015))
 out.append(v.m.add_cube('REF_FRONT_SPLITTER',(2.215,0,.160),(.012,1.300,.012),M['body_dark'],.003))
 # rear hierarchy without a separate body/fascia volume
 out.append(v.m.add_cube('REF_REAR_LIGHTBAR',(-2.250,0,.700),(.010,1.620,.015),M['tail'],.0025));out.append(v.m.add_cube('REF_REAR_GRILLE_PANEL',(-2.215,0,.790),(.012,.875,.080),M['body_dark'],.008))
 for k in range(11):out.append(v.m.add_cube(f'REF_REAR_GRILLE_VANE_{k:02d}',(-2.222,-.39+k*.078,.790),(.006,.020,.067),M['rim'],.0015))
 out.append(v.m.add_cube('REF_REAR_PLATE_RECESS',(-2.252,0,.450),(.010,.550,.080),M['body_dark'],.010));out.append(v.m.add_cube('REF_REAR_DIFFUSER',(-2.242,0,.245),(.012,1.250,.100),M['body_dark'],.012))
 for side in (1,-1):
  bpy.ops.mesh.primitive_torus_add(major_radius=.052,minor_radius=.008,major_segments=40,minor_segments=8,location=(-2.250,side*.485,.275),rotation=(0,math.pi/2,0));e=bpy.context.object;e.name='REF_EXHAUST_'+str(side);e.data.materials.append(M['rim']);out.append(e)
 return out
v.build_identity=build_identity

# Landmark receipt with current calibrated A/C aperture positions.
base_landmark=v.landmark_receipt
def landmark13(source_hash):
 d=base_landmark(source_hash)
 for item in d['landmarks']:
  item['candidate_measurement_source']='V13_FINAL_VISIBLE_GEOMETRY_OR_APERTURE'
  if item['id']=='A_PILLAR_BASE':item['candidate']=.650;item['normalized_error']=abs(.650-float(item['target']))/float(item['normalization'])
  if item['id']=='C_PILLAR_BASE':item['candidate']=-1.150;item['normalized_error']=abs(-1.150-float(item['target']))/float(item['normalization'])
 d['mass_families']=['ONE_CONTINUOUS_PRIMARY_SHELL','FRONT_FENDER_CROWN_SECTION','REAR_HAUNCH_SECTION','ROOF_FASTBACK_CONTINUITY','TERMINAL_PLAN_CURVATURE','APERTURE_HOST_CHAIN'];d['visible_primary_shell_count']=1;return d
v.landmark_receipt=landmark13

# Final evaluated-geometry measurement helpers.
def evaluated_vertices(obj):
 dg=bpy.context.evaluated_depsgraph_get();eo=obj.evaluated_get(dg);me=eo.to_mesh()
 try:return [eo.matrix_world@q.co for q in me.vertices]
 finally:eo.to_mesh_clear()
def panel_ratio(name,lower):
 o=bpy.data.objects[name];vs=[o.matrix_world@q.co for q in o.data.vertices];zs=[p.z for p in vs];zr=min(zs) if lower else max(zs);sel=[p for p in vs if abs(p.z-zr)<.03];return (max(p.y for p in sel)-min(p.y for p in sel))/v.WIDTH
def nearest_section(vs,x,tol=.035):return [p for p in vs if abs(p.x-x)<=tol]
def final_side_errors():
 body=bpy.data.objects['DERIVED_911_9922_BODY'];vs=evaluated_vertices(body);upper=[];lower=[]
 for x,t in SIDE_TOP:
  sec=nearest_section(vs,x);cand=max((p.z for p in sec),default=float('nan'));upper.append((x,t,cand,cand-t))
 for x,t in SIDE_LOW:
  sec=[p for p in nearest_section(vs,x,.040) if abs(p.y)>=.68]
  cand=min((p.z for p in sec),default=float('nan'));lower.append((x,t,cand,cand-t))
 def stat(rows):
  es=[r[3] for r in rows if math.isfinite(r[3])];return math.sqrt(sum(e*e for e in es)/len(es)),max(abs(e) for e in es)
 return upper,lower,stat(upper),stat(lower)
def projection_receipt():
 up,lo,(urmse,umax),(lrmse,lmax)=final_side_errors();fu=panel_ratio('REF_WINDSHIELD',False);fl=panel_ratio('REF_WINDSHIELD',True);rl=panel_ratio('REF_REAR_GLASS',True);t=PROJ['thresholds']
 metrics=[
  {'id':'SIDE_UPPER_VISIBLE_RMSE_M','target':0.0,'candidate':urmse,'abs_error':urmse,'limit':.035,'reference_target_source':'REFERENCE_CONTOUR_TARGETS_992_2.json:side_top_silhouette_m','candidate_measurement_source':'V13_FINAL_VISIBLE_UNION_PROJECTION'},
  {'id':'SIDE_LOWER_VISIBLE_RMSE_M','target':0.0,'candidate':lrmse,'abs_error':lrmse,'limit':.065,'reference_target_source':'REFERENCE_PROJECTION_TARGETS_992_2.json:side.lower_body_silhouette_m','candidate_measurement_source':'V13_FINAL_VISIBLE_UNION_PROJECTION'},
  {'id':'FRONT_UPPER_CABIN_WIDTH_RATIO','target':PROJ['front']['roof_width_ratio_at_upper_cabin'],'candidate':fu,'abs_error':abs(fu-PROJ['front']['roof_width_ratio_at_upper_cabin']),'limit':t['front_roof_width_ratio_abs_error_max'],'reference_target_source':'REFERENCE_PROJECTION_TARGETS_992_2.json:front.roof_width_ratio_at_upper_cabin','candidate_measurement_source':'V13_FINAL_WINDSHIELD_UPPER_MESH'},
  {'id':'FRONT_WINDSHIELD_LOWER_WIDTH_RATIO','target':PROJ['front']['windshield_lower_width_ratio'],'candidate':fl,'abs_error':abs(fl-PROJ['front']['windshield_lower_width_ratio']),'limit':t['front_windshield_lower_width_ratio_abs_error_max'],'reference_target_source':'REFERENCE_PROJECTION_TARGETS_992_2.json:front.windshield_lower_width_ratio','candidate_measurement_source':'V13_FINAL_WINDSHIELD_LOWER_MESH'},
  {'id':'REAR_BACKLIGHT_LOWER_WIDTH_RATIO','target':PROJ['rear']['backlight_lower_width_ratio'],'candidate':rl,'abs_error':abs(rl-PROJ['rear']['backlight_lower_width_ratio']),'limit':t['rear_backlight_lower_width_ratio_abs_error_max'],'reference_target_source':'REFERENCE_PROJECTION_TARGETS_992_2.json:rear.backlight_lower_width_ratio','candidate_measurement_source':'V13_FINAL_REAR_GLASS_LOWER_MESH'}]
 ok=all(m['abs_error']<=m['limit'] for m in metrics)
 return {'schema':'oleander.3d.rendered-projection-fidelity-receipt.v1','reference':'REFERENCE_PROJECTION_TARGETS_992_2.json + REFERENCE_CONTOUR_TARGETS_992_2.json','candidate_revision':'V13_CONTINUOUS_PRIMARY_SHELL','status':'PROJECTION_MACHINE_SCREENING_PASS' if ok else 'PROJECTION_MACHINE_SCREENING_FAIL','metrics':metrics,'side_upper_max_abs_m':umax,'side_lower_max_abs_m':lmax,'independent_visual_review':False,'reference_fidelity_review':'HOLD','does_not_prove':PROJ['does_not_prove']},up,lo

# Execute exactly once.
try:
 v.main()
except SystemExit:
 a=v.m.parse_args();out=Path(a.out).resolve()
 if (out/'REFERENCE_REPRO_QA.json').exists():
  pr,upper,lower=projection_receipt();(out/'REFERENCE_PROJECTION_RECEIPT.json').write_text(json.dumps(pr,ensure_ascii=False,indent=2)+'\n')
  # construction/visible binding now measures the final visible shell, not a hidden intermediate body.
  urmse=next(m['candidate'] for m in pr['metrics'] if m['id']=='SIDE_UPPER_VISIBLE_RMSE_M');umax=pr['side_upper_max_abs_m'];binding={'schema':'oleander.3d.reference-contour-binding.v2','reference':'REFERENCE_CONTOUR_TARGETS_992_2.json','candidate':'V13_FINAL_VISIBLE_UNION_PROJECTION','side_top_rmse_m':urmse,'side_top_max_abs_m':umax,'thresholds':CONTOUR['gates'],'samples':[{'x':x,'target_z':t,'candidate_z':c,'error_m':e,'reference_target_source':'REFERENCE_CONTOUR_TARGETS_992_2.json','candidate_measurement_source':'V13_FINAL_VISIBLE_UNION_PROJECTION'} for x,t,c,e in upper],'status':'MACHINE_BINDING_PASS' if urmse<=CONTOUR['gates']['side_top_rmse_m_max'] and umax<=CONTOUR['gates']['side_top_max_abs_m'] else 'MACHINE_BINDING_FAIL','does_not_prove':CONTOUR['does_not_prove']};(out/'REFERENCE_CONTOUR_BINDING_RECEIPT.json').write_text(json.dumps(binding,ensure_ascii=False,indent=2)+'\n')
  q=json.loads((out/'REFERENCE_REPRO_QA.json').read_text());q['reference_fidelity_revision']='V13_CONTINUOUS_PRIMARY_SHELL';q['projection_machine_gate']=pr['status'];q['reference_contour_binding']=binding['status'];q['visible_primary_shell_count']=1;q['continuous_primary_shell_gate']='MACHINE_STRUCTURE_PASS_VISUAL_REVIEW_REQUIRED';q['runtime_passes']=1;q['macro_form_gate']='MACHINE_SCREENING_ONLY_VISUAL_REVIEW_REQUIRED';q['design_quality_gate']='HOLD_FOR_INDEPENDENT_REFERENCE_COMPARISON';(out/'REFERENCE_REPRO_QA.json').write_text(json.dumps(q,ensure_ascii=False,indent=2)+'\n')
  r=json.loads((out/'REFERENCE_REPRO_RECEIPT.json').read_text());r['reference_fidelity_revision']='V13_CONTINUOUS_PRIMARY_SHELL';r['projection_machine_gate']=pr['status'];r['visual_reference_fidelity']='HOLD_INDEPENDENT_REVIEW';r['visible_primary_shell_count']=1;r['runtime_passes']=1;(out/'REFERENCE_REPRO_RECEIPT.json').write_text(json.dumps(r,ensure_ascii=False,indent=2)+'\n')
 raise
