import fs from "node:fs";
import path from "node:path";
import {fileURLToPath} from "node:url";
const root=path.dirname(fileURLToPath(import.meta.url));
const read=n=>fs.readFileSync(path.join(root,n),"utf8");
const html=read("index.html"),css=read("styles.css"),js=read("app.js");
const sections=[...html.matchAll(/data-section="(\d{2})"/g)].map(m=>Number(m[1]));
const contiguous=sections.length>0&&sections.every((n,i)=>n===i+1);
const anchors=["hero","assets","journey","brief","context","audience","idea","thinking","system","imprints","scenes","scene-r13","digital","physical","brandmemory","memory","technical","final"];
const requiredAssets=["assets/body_need_scenarios_current.svg","assets/brand_journey_current.svg","assets/brand_system_current.svg","assets/memory_journal_current.svg","assets/physical_body_support_hold.svg","assets/r06_attention_sequence_current.svg","assets/r06_detail_atlas_v11.svg","assets/r06_general_assembly_v11.svg","assets/r06_technical_relation_current.svg","assets/r13_passage_sequence_current.svg","assets/return_service_closure_current.svg","assets/route03_locked_current.svg","assets/technical_focus_v2.svg","assets/qj_hero_keep_v11_b64_01.txt","assets/qj_hero_keep_v11_b64_02a.txt","assets/qj_r06_landscape_keep_v11_b64_01.txt"];
const missing=requiredAssets.filter(r=>!fs.existsSync(path.join(root,r))||fs.statSync(path.join(root,r)).size===0);
const directVectors=requiredAssets.filter(r=>r.endsWith('.svg')).every(r=>html.includes(r));
const localQjd=js.includes('qj_hero_keep_v11_b64_01.txt')&&js.includes('qj_r06_landscape_keep_v11_b64_01.txt');
const externalImageRuntime=/https?:\/\/[^"'`\s]+\.(?:jpg|jpeg|png|webp)/i.test(html+"\n"+js);
const forbidden=[/112\s*页/i,/三个产品[^。]*项目主体/i].filter(p=>p.test(html)).map(p=>p.source);
const completionScoreRejected=html.includes("而非 13/13 完成率")||html.includes("而不是 13/13 完成率");
const completeReading=["L1 · PROJECT + EXPERIENCE","L2 · CONTEXT + ANALYSIS","L3 · DESIGN PRINCIPLES","L3 · DESIGN METHODS","PHYSICAL / BODY / SENSORY","BRAND + VISUAL IDENTITY","MEMORY / IP / TAKE-AWAY","DESIGN DEVELOPMENT + TECHNICAL PROOF","L6 · PROCESS / JUDGMENT / RETURN"].every(x=>html.includes(x));
const stateLogic=["NORMAL","DEGRADED","CLOSED","UNKNOWN","FULL / LIGHT / OFF"].every(x=>(html+js).includes(x));
const interaction=/imprints/.test(js)&&/syncPage/.test(js)&&/supplementTrigger/.test(html+js)&&/stateData/.test(js);
const result={schema:"C04_COMPLETE_SIMPLIFIED_STATIC_CHECK_V1",section_count:sections.length,section_numbers:sections,contiguous_section_numbering:contiguous,core_anchors_present:anchors.every(id=>html.includes(`id=\"${id}\"`)),complete_project_reading_present:completeReading,local_qjd_runtime_binding:localQjd,external_raster_image_dependency_present:externalImageRuntime,required_asset_count:requiredAssets.length,missing_or_empty_assets:missing,current_vectors_direct_bound:directVectors,state_and_fallback_logic_present:stateLogic,interactive_reading_present:interaction,responsive_css:/@media\(max-width:/i.test(css),reduced_motion_present:/prefers-reduced-motion\s*:\s*reduce/i.test(css)&&/prefers-reduced-motion:\s*reduce/i.test(js),remote_concept_boundary:html.includes("REMOTE CONCEPT / NOT SITE PHOTO")&&html.includes("不作为现场照片或测量证据"),model_scope_corrected:html.includes("不是产品总数")&&html.includes("不定义完整项目的产品数量"),completion_score_logic_rejected:completionScoreRejected,forbidden_public_compression_tokens:forbidden};
result.pass=result.contiguous_section_numbering&&result.core_anchors_present&&result.complete_project_reading_present&&result.local_qjd_runtime_binding&&!result.external_raster_image_dependency_present&&result.missing_or_empty_assets.length===0&&result.current_vectors_direct_bound&&result.state_and_fallback_logic_present&&result.interactive_reading_present&&result.responsive_css&&result.reduced_motion_present&&result.remote_concept_boundary&&result.model_scope_corrected&&result.completion_score_logic_rejected&&result.forbidden_public_compression_tokens.length===0;
fs.writeFileSync(path.join(root,"C04_WEB_v1_12_R2_STATIC_READBACK.json"),JSON.stringify(result,null,2)+"\n");
console.log(JSON.stringify(result,null,2));
if(!result.pass)process.exit(1);
