#!/usr/bin/env python3
from __future__ import annotations
import sys
from pathlib import Path

def main():
    if len(sys.argv)!=2:
        print('usage: build_motion_extension_02_demo.py OUTPUT.html'); raise SystemExit(2)
    out=Path(sys.argv[1])
    doc='''<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>OLEANDER Motion Extension 02</title><style>
:root{--paper:#f3f0e8;--ink:#17231f;--muted:#68716c;--teal:#4d8d92;--rust:#a95a4e}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font-family:system-ui,sans-serif}main{max-width:1120px;margin:auto;padding:34px}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:20px}.card{min-height:270px;background:#faf8f2;border:1px solid #c9c5b8;border-radius:15px;padding:16px;overflow:hidden}.k{font:700 10px/1.2 ui-monospace,monospace;letter-spacing:.08em;color:var(--muted)}.demo{height:190px;position:relative;margin-top:12px;border-top:1px solid #ded9ce;overflow:hidden}.morph{width:88px;height:88px;background:var(--teal);clip-path:polygon(50% 0,100% 50%,50% 100%,0 50%);position:absolute;left:70px;top:50px;transition:clip-path 420ms cubic-bezier(.65,0,.35,1),transform 420ms cubic-bezier(.65,0,.35,1)}.morph.b{clip-path:polygon(0 10%,100% 0,88% 100%,18% 82%);transform:translateX(120px) rotate(8deg)}.ktype{font-size:48px;font-weight:450;letter-spacing:-.04em;position:absolute;left:32px;top:60px;transition:font-weight 360ms cubic-bezier(.16,1,.3,1),letter-spacing 360ms cubic-bezier(.16,1,.3,1)}.ktype.on{font-weight:700;letter-spacing:.015em}.viewA,.viewB{position:absolute;inset:25px;border:1px solid #9d9b92;border-radius:12px;display:grid;place-items:center;transition:opacity 320ms cubic-bezier(.65,0,.35,1),transform 320ms cubic-bezier(.65,0,.35,1)}.viewB{opacity:0;transform:translateX(36px) scale(.98)}.viewstage.b .viewA{opacity:0;transform:translateX(-36px) scale(.98)}.viewstage.b .viewB{opacity:1;transform:none}.dragtrack{position:absolute;left:25px;right:25px;top:90px;height:4px;background:#d4d0c5}.handle{position:absolute;left:28px;top:71px;width:40px;height:40px;border-radius:50%;background:var(--rust);cursor:grab;touch-action:none}.cursorArea{position:absolute;inset:22px;border:1px dashed #a6a39a;border-radius:12px}.cursorDot{position:absolute;left:50%;top:50%;width:56px;height:56px;margin:-28px;border:2px solid var(--teal);border-radius:12px;display:grid;place-items:center;transition:transform 160ms cubic-bezier(.16,1,.3,1)}button{border:1px solid #aaa69a;background:white;border-radius:8px;padding:6px 9px}@media(max-width:760px){.grid{grid-template-columns:1fr}}@media(prefers-reduced-motion:reduce){.morph,.ktype,.viewA,.viewB,.cursorDot{transition:none!important}}
</style></head><body><main><div class="k">OLEANDER / CONDITIONAL MOTION EXTENSION 02</div><h1>Native mechanism smoke demo</h1><p style="color:var(--muted)">Conditional mechanisms only. Static endpoint, normal pointer/navigation and Reduced Motion remain authoritative fallbacks.</p><div class="grid">
<section class="card"><div class="k">TD-MR13 / EF-04</div><b>Topology-safe morph mechanism</b> <button id="morphBtn">toggle</button><div class="demo"><div id="morph" class="morph"></div><small style="position:absolute;bottom:10px;left:12px;color:var(--muted)">Synthetic shape only; real use requires endpoint + correspondence audit.</small></div></section>
<section class="card"><div class="k">TD-MR15 / EF-17</div><b>Kinetic type emphasis</b> <button id="typeBtn">toggle</button><div class="demo"><div id="ktype" class="ktype">SECTION</div></div></section>
<section class="card"><div class="k">TD-MR19 / EF-10</div><b>View transition with stable anchor</b> <button id="viewBtn">toggle</button><div id="viewstage" class="demo viewstage"><div class="viewA">FIG-01 / BOARD</div><div class="viewB">FIG-01 / DETAIL</div></div></section>
<section class="card"><div class="k">TD-MR20 / EF-11</div><b>Interruptible drag handle</b><div class="demo"><div class="dragtrack"></div><div id="handle" class="handle" role="slider" tabindex="0" aria-valuemin="0" aria-valuemax="100" aria-valuenow="0"></div></div></section>
<section class="card"><div class="k">TD-MR17 / EF-19</div><b>Local cursor response</b><div id="cursorArea" class="demo cursorArea"><div id="cursorDot" class="cursorDot" tabindex="0">DETAIL</div></div></section>
<section class="card"><div class="k">TD-MR18 / EF-20</div><b>Smooth-scroll infrastructure</b><div class="demo" style="padding:22px;color:var(--muted)">Not enabled in this smoke demo. Native scroll is deliberately retained as the baseline. The recipe requires a project-specific synchronization reason before transport interpolation is allowed.</div></section>
</div><p class="k">SYNTHETIC RUNTIME SMOKE ONLY · NO AR-S10 PASS · NO DESIGN KEEP</p></main><script>
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;const morph=document.getElementById('morph');document.getElementById('morphBtn').onclick=()=>morph.classList.toggle('b');const kt=document.getElementById('ktype');document.getElementById('typeBtn').onclick=()=>kt.classList.toggle('on');const vs=document.getElementById('viewstage');document.getElementById('viewBtn').onclick=()=>vs.classList.toggle('b');
const h=document.getElementById('handle'),demo=h.parentElement;let dragging=false;function setX(px){const min=28,max=demo.clientWidth-68;px=Math.max(min,Math.min(max,px));h.style.left=px+'px';const v=Math.round((px-min)/(max-min)*100);h.setAttribute('aria-valuenow',v)}h.addEventListener('pointerdown',e=>{dragging=true;h.setPointerCapture(e.pointerId)});h.addEventListener('pointermove',e=>{if(dragging)setX(e.clientX-demo.getBoundingClientRect().left-20)});h.addEventListener('pointerup',()=>dragging=false);h.addEventListener('keydown',e=>{let v=Number(h.getAttribute('aria-valuenow'));if(e.key==='ArrowRight')v+=5;else if(e.key==='ArrowLeft')v-=5;else return;e.preventDefault();const min=28,max=demo.clientWidth-68;setX(min+(max-min)*Math.max(0,Math.min(100,v))/100)});
const area=document.getElementById('cursorArea'),dot=document.getElementById('cursorDot');area.addEventListener('pointermove',e=>{if(reduced)return;const r=area.getBoundingClientRect();const dx=((e.clientX-r.left)/r.width-.5)*12,dy=((e.clientY-r.top)/r.height-.5)*12;dot.style.transform=`translate(${dx}px,${dy}px)`});area.addEventListener('pointerleave',()=>dot.style.transform='none');
</script></body></html>'''
    out.parent.mkdir(parents=True,exist_ok=True);out.write_text(doc,encoding='utf-8');required=['prefers-reduced-motion','TD-MR13','TD-MR15','TD-MR17','TD-MR18','TD-MR19','TD-MR20','aria-valuenow'];miss=[x for x in required if x not in doc];
    if miss: raise SystemExit('FAIL missing '+repr(miss))
    print(f'PASS: generated {out}; conditional native mechanisms + reduced-motion marker present')
if __name__=='__main__': main()
