import fs from 'node:fs';import path from 'node:path';import {chromium} from 'playwright';
const out=path.resolve(process.env.OLEANDER_OUT||'out/TRI_BROWSER');const src=JSON.parse(fs.readFileSync(path.resolve(process.env.OLEANDER_SOURCE_RECEIPT||'out/TRI_SOURCE/SOURCE_RECEIPT.json'),'utf8'));fs.mkdirSync(out,{recursive:true});
const norm=v=>{const l=Math.hypot(...v);return v.map(x=>x/l)};const cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];const scale=(v,s)=>v.map(x=>x*s);const add3=(a,b,c)=>a.map((x,i)=>x+b[i]+c[i]);const avg=vs=>norm(vs.reduce((a,v)=>a.map((x,i)=>x+v[i]),[0,0,0]).map(x=>x/vs.length));const dot=(a,b)=>a.reduce((s,x,i)=>s+x*b[i],0);const angle=(a,b)=>Math.acos(Math.max(-1,Math.min(1,dot(norm(a),norm(b)))))*180/Math.PI;const maxDelta=(a,b)=>Math.max(...a.map((x,i)=>Math.abs(x-b[i])));const distance=(a,b)=>Math.hypot(...a.map((x,i)=>x-b[i]));const gate=(a,b)=>{const angularErrorDeg=angle(a,b),componentMaxAbsDelta=maxDelta(a,b);return {angularErrorDeg,componentMaxAbsDelta,pass:angularErrorDeg<=.005&&componentMaxAbsDelta<=5e-5}};const posKey=v=>v.map(x=>Number(x).toFixed(6)).join(',');const triKey=ps=>[...ps].map(posKey).sort().join('|');
const browser=await chromium.launch({headless:true,args:['--use-gl=swiftshader','--enable-webgl','--ignore-gpu-blocklist','--disable-dev-shm-usage']});const page=await browser.newPage({viewport:{width:720,height:720},deviceScaleFactor:1});const logs=[];page.on('console',m=>logs.push(`${m.type()}: ${m.text()}`));page.on('pageerror',e=>logs.push(`pageerror: ${e.message}`));await page.goto('http://127.0.0.1:4178/viewer.html',{waitUntil:'networkidle'});await page.waitForFunction(()=>window.__OLEANDER_TRI_RUNTIME__?.ready||window.__OLEANDER_TRI_RUNTIME__?.error,{timeout:30000});const rt=await page.evaluate(()=>window.__OLEANDER_TRI_RUNTIME__);if(rt.error)throw new Error(rt.error);
const q=src.tangent_space_sample,checks={};
for(const name of ['TRIANGULATION_A','TRIANGULATION_B']){
 const got=rt.objects[name],source=src.objects[name];if(!got||!got.positionPresent||!got.normalPresent||!got.tangentPresent||!got.uvPresent)throw new Error(`missing attributes ${name}`);if(got.indices.length%3)throw new Error(`non-triangle target index count ${name}`);
 const sourceByKey=new Map(source.triangles.map(t=>[t.triangle_key,t]));const cornerChecks=[],targetBySourceVertex={};let matchedTriangles=0;
 for(let ti=0;ti<got.indices.length;ti+=3){const idx=got.indices.slice(ti,ti+3),positions=idx.map(i=>got.worldPositions[i]),key=triKey(positions),st=sourceByKey.get(key);if(!st)throw new Error(`no source triangle match ${name} ${key}`);matchedTriangles++;
  for(const i of idx){const p=got.worldPositions[i],sc=[...st.corners].sort((a,b)=>distance(a.position_target_world,p)-distance(b.position_target_world,p))[0],pd=distance(sc.position_target_world,p);if(pd>5e-5)throw new Error(`corner position mismatch ${name} d=${pd}`);const T=norm(got.worldTangents[i]),N=norm(got.worldNormals[i]),w=got.tangentW[i]<0?-1:1,B=norm(scale(cross(N,T),w)),P=norm(add3(scale(T,q[0]),scale(B,q[1]),scale(N,q[2])));const uv=got.uvs[i];const errors={tangent:gate(T,sc.tangent_target_world),normal:gate(N,sc.normal_target_world),bitangent:gate(B,sc.bitangent_target_world),perturbed:gate(P,sc.perturbed_target_world)};const uvMaxDelta=maxDelta(uv,sc.uv);const pass=Object.values(errors).every(x=>x.pass)&&w===sc.w&&uvMaxDelta<=1e-6;cornerChecks.push({targetIndex:i,sourceVertex:sc.vertex,positionDistance:pd,uvMaxDelta,w,expectedW:sc.w,errors,pass});(targetBySourceVertex[String(sc.vertex)]??=[]).push(P);}
 }
 const targetVertexPerturbed={};const vertexErrors={};for(const [vi,ps] of Object.entries(targetBySourceVertex)){targetVertexPerturbed[vi]=avg(ps);vertexErrors[vi]=gate(targetVertexPerturbed[vi],source.vertex_perturbed_target[vi]);}
 checks[name]={vertexCount:got.vertexCount,indexCount:got.indexCount,matchedTriangles,cornerCount:cornerChecks.length,allCornersPass:cornerChecks.every(c=>c.pass),cornerChecks,targetVertexPerturbed,vertexErrors,allVertexAggregatesPass:Object.values(vertexErrors).every(e=>e.pass),normalMap:got.material?.normalMap===true};
}
const targetDeltas={};for(const vi of ['0','1','2','3'])targetDeltas[vi]=angle(checks.TRIANGULATION_A.targetVertexPerturbed[vi],checks.TRIANGULATION_B.targetVertexPerturbed[vi]);const sourceDeltas=src.source_vertex_perturbed_angle_delta_deg;const deltaDrift={};for(const vi of ['0','1','2','3'])deltaDrift[vi]=Math.abs(targetDeltas[vi]-sourceDeltas[vi]);const sourceMax=Math.max(...Object.values(sourceDeltas)),targetMax=Math.max(...Object.values(targetDeltas)),maxDrift=Math.max(...Object.values(deltaDrift));const cornerParity=Object.values(checks).every(c=>c.matchedTriangles===2&&c.cornerCount===6&&c.allCornersPass&&c.allVertexAggregatesPass&&c.normalMap);const sensitivityPreserved=sourceMax>.1&&targetMax>.1&&maxDrift<=.01;const overall=cornerParity&&sensitivityPreserved;
await page.screenshot({path:path.join(out,'TRIANGULATION_TBN_BROWSER_720.png'),fullPage:true});const receipt={schema:'oleander.3d.gltf-triangulation-tbn-target.v2',browser:'Chromium via Playwright 1.55.0',threeRevision:rt.threeRevision,sourceAsset:src.asset,sourceAssetSha256:src.asset_sha256,objectChecks:checks,sourceVertexPerturbedAngleDeltaDeg:sourceDeltas,targetVertexPerturbedAngleDeltaDeg:targetDeltas,vertexSensitivityDeltaDriftDeg:deltaDrift,maxSensitivityDeltaDriftDeg:maxDrift,sourceMaxSensitivityDeg:sourceMax,targetMaxSensitivityDeg:targetMax,cornerParity,sensitivityPreserved,overallPass:overall,webgl:rt.webgl,screenshot:'TRIANGULATION_TBN_BROWSER_720.png',console:logs,evidenceClass:overall?'TARGET_RUNTIME_TRIANGLE_CORNER_TBN_PARITY_AND_TRIANGULATION_SENSITIVITY':'TARGET_RUNTIME_TRIANGLE_CORNER_TBN_UNRESOLVED',promotionScope:overall?['same positions + same UV + alternate triangulation produces measurably different tangent-space perturbed normals','each exported target triangle is matched to the explicit Blender source triangle by world-position signature','T/N/w/B/perturbed-normal parity is validated per matched face corner rather than across mismatched aggregate sampling domains','triangulation sensitivity survives Blender glTF export and Three target-runtime readback in this controlled witness']:[],provenanceNote:'The v1 aggregate gate failure is retained: six Blender loop samples were incorrectly compared with four indexed target vertices. v2 changes the comparison domain, not the tolerance for the original aggregate.',holds:['actual pixel shader output parity','production retopo mesh','cross-DCC MikkTSpace parity','post-bake triangulation mutation after another importer recomputes tangents','Design KEEP']};fs.writeFileSync(path.join(out,'TARGET_RUNTIME_RECEIPT.json'),JSON.stringify(receipt,null,2)+'\n');console.log(JSON.stringify(receipt,null,2));await browser.close();
